/**
 * Created by sam on 14/07/2016.
 */
export default {
  EDIT_CONFIG: 'EDIT_CONFIG',
  LOADING_CONFIG: 'LOADING_CONFIG',
  EDITING_OPTION: 'EDITING_OPTION',
  OPTION_EDIT_CANCEL: 'OPTION_EDIT_CANCEL',
  SAVING_OPTION: 'SAVING_OPTION',
  OPTION_SAVE_SUCCESS: 'OPTION_SAVE_SUCCESS',
  OPTION_SAVE_FAILURE: 'OPTION_SAVE_FAILURE',
  DELETING_OPTION: 'DELETING_OPTION',
  OPTION_DELETE_SUCCESS: 'OPTION_DELETE_SUCCESS',
  OPTION_DELETE_FAILURE: 'OPTION_DELETE_FAILURE',
  ADDING_OPTION: 'ADDING_OPTION',
  OPTION_ADD_SUCCESS: 'OPTION_ADD_SUCCESS',
  OPTION_ADD_FAILURE: 'OPTION_ADD_FAILURE',
  TOGGLE_ADD_OPTION_POPOVER:  'TOGGLE_ADD_OPTION_POPOVER',
  HIDE_ADD_OPTION_POPOVER: 'HIDE_ADD_OPTION_POPOVER',
  UPDATE_NEW_SECTION_NAME: 'UPDATE_NEW_SECTION_NAME',
  UPDATE_NEW_OPTION_NAME: 'UPDATE_NEW_OPTION_NAME',
  UPDATE_NEW_OPTION_VALUE: 'UPDATE_NEW_OPTION_VALUE',
  CONFIG_TABLE_UPDATED: 'CONFIG_TABLE_UPDATED'
};
