/**
 * Created by sam on 14/07/2016.
 */
export default {
  EDIT_CONFIG: 'EDIT_CONFIG',
  LOADING_CONFIG: 'LOADING_CONFIG',
  EDITING_OPTION: 'EDITING_OPTION',
  OPTION_EDIT_CANCEL: 'OPTION_EDIT_CANCEL',
  SAVING_OPTION: 'SAVING_OPTION',
  OPTION_SAVE_SUCCESS: 'OPTION_SAVE_SUCCESS',
  OPTION_SAVE_FAILURE: 'OPTION_SAVE_FAILURE'
};
